import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Mengimpor font Inter dengan subsets latin dan berbagai weight
const interFont = Inter({
  subsets: ["latin"],
  weight: ["600", "600", "600", "700"], // Tambahkan weight sesuai kebutuhan
  variable: "--font-inter", // Variabel CSS untuk font Inter
});

export const metadata: Metadata = {
  title: "Riyouuyt Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
